Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -12,10 +12,10 @@ jobs:
 
     steps:
     - name: Checkout repository
-      uses: actions/checkout@v3  # Update to latest version
+      uses: actions/checkout@v3
 
     - name: Setup .NET
-      uses: actions/setup-dotnet@v3  # Update to latest version
+      uses: actions/setup-dotnet@v3
       with:
         dotnet-version: '8.0.x'
 
@@ -34,10 +34,18 @@ jobs:
     - name: Test Projects
       run: dotnet test IsolinesProj/IsolinesProj.sln --configuration Release --verbosity normal
 
+    - name: Install Statiq CLI Tool
+      run: dotnet tool install Statiq.Tool --global || echo "Failed to install Statiq CLI tool"
+
+    - name: Update PATH for Statiq CLI Tool
+      run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH
+
+    - name: Verify Statiq CLI Tool Installation
+      run: dotnet tool list --global || echo "Statiq CLI tool not found. Check if it's correctly installed and in PATH."
+
     - name: Generate Documentation
       run: |
-        cd IsolinesProj
-        dotnet statiq build --input . --output site || echo "Statiq build failed. Check if Statiq.Web.GitHub is correctly installed."
+        statiq build --input IsolinesProj --output site || echo "Statiq build failed. Check if Statiq.Tool is correctly installed."
 
     - name: Update README.md with Documentation
       run: |
