Update dotnet.yml
Statiq.Web Problembehebung

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -2,7 +2,7 @@ name: .NET General Workflow
 
 on:
   push:
-    branches: [ isolinebranch ]
+    branches: [ isonlinebranch ]
   pull_request:
     branches: [ main ]
 
@@ -19,6 +19,21 @@ jobs:
       with:
         dotnet-version: '8.0.x'
 
+    - name: Create Tool Manifest
+      run: dotnet new tool-manifest
+
+    - name: Install Statiq CLI
+      run: dotnet tool install Statiq.Web.GitHub --version 1.0.0-beta.60
+
+    - name: Update PATH for Statiq CLI
+      run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH
+
+    - name: Verify Statiq CLI Installation
+      run: dotnet tool list
+
+    - name: Verify Statiq CLI Version
+      run: statiq --version || echo "Statiq CLI not found. Check the installation path and version."
+
     - name: Restore Dependencies
       run: dotnet restore IsolinesProj/IsolinesProj.sln
 
@@ -31,23 +46,10 @@ jobs:
     - name: Test Projects
       run: dotnet test IsolinesProj/IsolinesProj.sln --configuration Release --verbosity normal
 
-    - name: Install Statiq CLI
-      run: |
-        dotnet tool install -g Statiq.Web --version 1.0.0-beta.60 || echo "Statiq.Web CLI could not be installed. Check if the package name is correct or if it is available in NuGet."
-
-    - name: Update PATH for Statiq CLI
-      run: |
-        echo "Updating PATH for Statiq CLI"
-        echo "::add-path::${HOME}/.dotnet/tools"
-
-    - name: Verify Statiq CLI Installation
-      run: |
-        statiq --version || echo "Statiq CLI not found. Check the installation path and version."
-
     - name: Generate Documentation
       run: |
         cd IsolinesProj
-        statiq build --input . --output site || echo "Statiq build failed. Check if Statiq.Web is correctly installed."
+        statiq build --input . --output site || echo "Statiq build failed. Check if Statiq.Web.GitHub is correctly installed."
 
     - name: Update README.md with Documentation
       run: |
