Update dotnet.yml
Ich versuche das Problem über add package zu beheben.

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -22,8 +22,8 @@ jobs:
     - name: Restore Dependencies
       run: dotnet restore IsolinesProj/IsolinesProj.sln
 
-    - name: Install Statiq.Web.GitHub Package
-      run: dotnet add IsolinesProj/IsolinesProj.csproj package Statiq.Web.GitHub --version 1.0.0-beta.60
+    - name: Add Statiq.Web.GitHub Package
+      run: dotnet add package Statiq.Web.GitHub --version 1.0.0-beta.60
 
     - name: Build Main Solution
       run: dotnet build IsolinesProj/IsolinesProj.sln --no-restore --configuration Release
@@ -37,7 +37,7 @@ jobs:
     - name: Generate Documentation
       run: |
         cd IsolinesProj
-        dotnet run --project IsolinesProj/IsolinesProj.csproj statiq build --input . --output site || echo "Statiq build failed. Check if Statiq.Web.GitHub is correctly installed."
+        statiq build --input . --output site || echo "Statiq build failed. Check if Statiq.Web.GitHub is correctly installed."
 
     - name: Update README.md with Documentation
       run: |
