Update dotnet.yml
Das Problem mit Statiq.Web bestand weiterhin. Deshalb habe ich weitere Änderungen vorgenommen, um das Problem hoffentlich zu beheben.

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -32,18 +32,21 @@ jobs:
       run: dotnet test IsolinesProj/IsolinesProj.sln --configuration Release --verbosity normal
 
     - name: Install Statiq CLI
-      run: dotnet tool install --global Statiq.Web
+      run: dotnet tool install --global Statiq.Web.GitHub
 
     - name: Update PATH for Statiq CLI
       run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH
 
     - name: Verify Statiq CLI Installation
+      run: dotnet tool list --global
+
+    - name: Verify Statiq CLI Version
       run: statiq --version || echo "Statiq CLI not found. Check the installation path and version."
 
     - name: Generate Documentation
       run: |
         cd IsolinesProj
-        statiq build --input . --output site || echo "Statiq build failed. Check if Statiq.Web is correctly installed."
+        statiq build --input . --output site || echo "Statiq build failed. Check if Statiq.Web.GitHub is correctly installed."
 
     - name: Update README.md with Documentation
       run: |
